galaxy_info:
  author: G. Roggemans
  description: A role for common host settings.
  company: GROG
  license: MIT
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - all
  #  - 5
  #  - 6
  #  - 7
  #- name: GenericUNIX
  #  versions:
  #  - all
  #  - any
  #- name: Solaris
  #  versions:
  #  - all
  #  - 10
  #  - 11.0
  #  - 11.1
  #  - 11.2
  #  - 11.3
  #- name: Fedora
  #  versions:
  #  - all
  #  - 16
  #  - 17
  #  - 18
  #  - 19
  #  - 20
  #  - 21
  #  - 22
  #- name: Windows
  #  versions:
  #  - all
  #  - 2012R2
  #- name: SmartOS
  #  versions:
  #  - all
  #  - any
  #- name: opensuse
  #  versions:
  #  - all
  #  - 12.1
  #  - 12.2
  #  - 12.3
  #  - 13.1
  #  - 13.2
  #- name: Amazon
  #  versions:
  #  - all
  #  - 2013.03
  #  - 2013.09
  #- name: GenericBSD
  #  versions:
  #  - all
  #  - any
  #- name: FreeBSD
  #  versions:
  #  - all
  #  - 8.0
  #  - 8.1
  #  - 8.2
  #  - 8.3
  #  - 8.4
  #  - 9.0
  #  - 9.1
  #  - 9.1
  #  - 9.2
  - name: Ubuntu
    versions:
    - all
  #  - lucid
  #  - maverick
  #  - natty
  #  - oneiric
  #  - precise
  #  - quantal
  #  - raring
  #  - saucy
  #  - trusty
  #  - utopic
  #  - vivid
  #- name: SLES
  #  versions:
  #  - all
  #  - 10SP3
  #  - 10SP4
  #  - 11
  #  - 11SP1
  #  - 11SP2
  #  - 11SP3
  #- name: GenericLinux
  #  versions:
  #  - all
  #  - any
  - name: Debian
    versions:
    - all
  #  - etch
  #  - jessie
  #  - lenny
  #  - squeeze
  #  - wheezy
  galaxy_tags:
    - common
    - system

dependencies:
  - role: GROG.group
    version: v1.1.2
    when: >
      (group|string in 'True.true.Yes.yes')

  - role: GROG.management-user
    version: v1.2.7
    when: >
      (management_user|string in 'True.true.Yes.yes')

  - role: GROG.debug
    version: v1.2.3
    when: >
      (debug|string in 'True.true.Yes.yes')

  - role: GROG.fqdn
    version: v1.0.2
    when: >
      (fqdn|string in 'True.true.Yes.yes')

  - role: GROG.package
    version: v1.2.2
    when: >
      (package|string in 'True.true.Yes.yes')

  - role: willshersystems.sshd
    version: v0.4.5
    when: >
      (sshd|string not in 'False.false.No.no')

  - role: yatesr.timezone
    version: 1.0.0
    when: >
      (timezone|string not in 'False.false.No.no')

  - role: geerlingguy.firewall
    version: 1.0.9
    when: >
      (firewall|string in 'True.true.Yes.yes')
    firewall_allowed_tcp_ports:
      - 22
