---
- name: Make sure rpm dir is available
  file:
    path: "{{ rpm_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: rsync {{ rpm_dir }} files 
  copy:
    src: "{{ rpm_dir }}"
    dest: "{{ rpm_dir }}"

- name: install java rpm file
  yum: name={{ rpm_dir }}{{ java_rpm_package }}
       state=present

- name: setting java environment
  lineinfile: path=/etc/profile
              line={{item}}
  with_items:
    - '#set java environment'
    - 'export JAVA_HOME=/usr/java/jdk1.8.0_65'
    - 'export JRE_HOME=$JAVA_HOME/jre'
    - 'export PATH=$JAVA_HOME/bin:$PATH'
    - 'export CLASSPATH=$JAVA_HOME/lib:$CLASSPATH'
    
